- name: Check if erlang_cookie is set
  fail:
    msg: "erlang_cookie var is not defined - set it using '-e' option"
  when: erlang_cookie is not defined

- name: Create list of rabbitmq server names
  set_fact:
    rabbitmq_hosts: "{{ groups['rabbitmq']|map('extract', hostvars, ['ansible_hostname'])|list }}"

- name: Get hostname of first host in group
  set_fact:
    rabbitmq_first_host: "{{ hostvars[groups['rabbitmq'][0]]['ansible_hostname'] }}"

- name: Remove preinstalled erlang
  yum:
    name: erlang-erts-R16B-03.18.el7.x86_64
    state: absent

- name: Ensure erlang is installed
  yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.0.2-2~centos~7_amd64.rpm
    state: present

- name: Install rabbitmq-server
  yum:
    name: "{{ rabbitmq_server_rpm_url }}"
    state: present

- name: Ensure rabbitmq service is enabled
  service:
    name: rabbitmq-server
    enabled: yes

- name: Configure rabbitmq server
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq-server

- name: Configure rabbitmq plugins
  template:
    src: enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
  notify: Restart rabbitmq-server

- name: Copy erlang cookie to servers
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify: Restart rabbitmq-server

- name: Start first host
  service:
    name: rabbitmq-server
    state: started
  when: ansible_hostname == rabbitmq_first_host

- name: Wait for first host
  wait_for:
    port: 5672
    host: "{{ rabbitmq_first_host }}"
  when: ansible_hostname != rabbitmq_first_host

- name: Start all servers
  service:
    name: rabbitmq-server
    state: started

- name: Install python3 (required for rabbitmqadmin)
  yum:
    name: python3
    state: present
  when: ansible_hostname == rabbitmq_first_host

- name: Download rabbitmqadmin
  get_url:
    url: http://{{ rabbitmq_first_host }}:15672/cli/rabbitmqadmin
    dest: /usr/sbin
  when: ansible_hostname == rabbitmq_first_host

- name: Make rabbitmqadmin executable
  file: dest=/usr/sbin/rabbitmqadmin mode=a+x
  when: ansible_hostname == rabbitmq_first_host

- name: Create queue
  command: rabbitmqadmin declare queue name="quorum.mqperf" queue_type=quorum
  when: ansible_hostname == rabbitmq_first_host
