---
- set_fact: rocketmq_name_server="{{ groups['rocketmq'][0] }}"
- set_fact: rocketmq_broker_master="{{ groups['rocketmq'][1] }}"
- set_fact: rocketmq_broker_slave_1="{{ groups['rocketmq'][2] }}"
- set_fact: rocketmq_broker_slave_2="{{ groups['rocketmq'][3] }}"
- set_fact: rocketmq_name_server_private_ip="{{ hostvars[rocketmq_name_server].ec2_private_ip_address }}"

- name: Remove Java 7
  yum:
    name: java-1.7.0-openjdk
    state: absent
  become: true
  
- name: Install Java 8
  yum:
    name: java-1.8.0-openjdk-devel.x86_64
    state: present
  become: true

- name: Set JAVA_HOME
  lineinfile: 
    dest: /etc/environment 
    state: present 
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'

- name: Link java
  file:
    state: link
    src: /usr/lib/jvm/java-1.8.0-openjdk
    dest: /usr/java

- name: Set name server hostname 
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "rocketmq_name_server"
  with_items:
    - "{{ rocketmq_name_server }}"

- name: Update /etc/hosts 
  run_once: true
  delegate_to: "{{ item }}"
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 rocketmq_name_server"
  with_items:
    - "{{ rocketmq_name_server }}"

- name: Set broker master hostname 
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "rocketmq_broker_master"
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Update /etc/hosts 
  run_once: true
  delegate_to: "{{ item }}"
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 rocketmq_broker_master"
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Set slave 1 hostname 
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "rocketmq_broker_slave_1"
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"

- name: Update /etc/hosts 
  run_once: true
  delegate_to: "{{ item }}"
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 rocketmq_broker_slave_1"
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"

- name: Set slave 2 hostname 
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "rocketmq_broker_slave_2"
  with_items:
    - "{{ rocketmq_broker_slave_2 }}"

- name: Update /etc/hosts 
  run_once: true
  delegate_to: "{{ item }}"
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 rocketmq_broker_slave_2"
  with_items:
    - "{{ rocketmq_broker_slave_2 }}"

- name: Download RocketMQ
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /opt
    remote_src: yes

- name: Create convenient link
  file:
    state: link
    src: /opt/rocketmq-all-{{ rocketmq_version }}-bin-release
    dest: /opt/rocketmq

- name: Setting Environment
  shell: |
    echo 'export PATH="$PATH:{{ rocketmq_dir }}/bin"' >> /etc/profile
    echo 'export NAMESRV_ADDR={{ rocketmq_name_server_private_ip }}:9876'

- name: Configuration RocketMQ Name Server
  run_once: true
  delegate_to: "{{ item }}"
  copy:
    src: mqnamesrv.service
    dest: /lib/systemd/system/
  with_items:
    - "{{ rocketmq_name_server }}"

- name: Reload daemon service on nameserver
  run_once: true
  delegate_to: "{{ item }}"
  shell: systemctl daemon-reload
  with_items:
    - "{{ rocketmq_name_server }}"

- name: Start RocketMQ Name Server
  run_once: true
  delegate_to: "{{ item }}"
  service:
    name: mqnamesrv
    state: started
    enabled: yes
  with_items:
    - "{{ rocketmq_name_server }}"

- name: Wait for mqnameserver to start
  wait_for: 
    host: "{{ item }}"
    port: "{{ rocketmq_name_server_port }}"
    delay: 10
    timeout: 640
    state: started
  with_items: 
    - "{{ rocketmq_name_server }}"
    
- name: Copy master.properties to master
  run_once: true
  delegate_to: "{{ item }}"
  copy:
    src: master.properties
    dest: /opt/rocketmq/master.properties
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Configuration master RocketMQ Broker Server
  run_once: true
  delegate_to: "{{ item }}"
  template:
    src: mqbroker-master.service.j2
    dest: /lib/systemd/system/mqbroker.service
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Reload daemon service on master
  run_once: true
  delegate_to: "{{ item }}"
  shell: systemctl daemon-reload
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Start master RocketMQ Broker Server
  run_once: true
  delegate_to: "{{ item }}"
  service:
    name: mqbroker
    state: started
    enabled: yes
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Wait for master mqbroker to start
  wait_for:
    host: "{{ item }}"
    port: "{{ rocketmq_broker_port_main }}"
    delay: 10
    timeout: 640
    state: started
  with_items:
    - "{{ rocketmq_broker_master }}"

- name: Copy slave.properties to slave 1
  run_once: true
  delegate_to: "{{ item }}"
  copy:
    src: slave_1.properties
    dest: /opt/rocketmq/slave.properties
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"

- name: Copy slave.properties to slaves 2
  run_once: true
  delegate_to: "{{ item }}"
  copy:
    src: slave_2.properties
    dest: /opt/rocketmq/slave.properties
  with_items:
    - "{{ rocketmq_broker_slave_2 }}"

- name: Configuration slaves RocketMQ Broker Server
  run_once: true
  delegate_to: "{{ item }}"
  template:
    src: mqbroker-slave.service.j2
    dest: /lib/systemd/system/mqbroker.service
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"
    - "{{ rocketmq_broker_slave_2 }}"

- name: Reload daemon service on slaves
  run_once: true
  delegate_to: "{{ item }}"
  shell: systemctl daemon-reload
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"
    - "{{ rocketmq_broker_slave_2 }}"

- name: Start slave 1
  run_once: true
  delegate_to: "{{ item }}"
  service:
    name: mqbroker
    state: started
    enabled: yes
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"

- name: Wait for slave 1 broker to start
  wait_for:
    host: "{{ item }}"
    port: "{{ rocketmq_broker_port_main }}"
    delay: 10
    timeout: 640
    state: started
  with_items:
    - "{{ rocketmq_broker_slave_1 }}"

- name: Start slave 2
  run_once: true
  delegate_to: "{{ item }}"
  service:
    name: mqbroker
    state: started
    enabled: yes
  with_items:
    - "{{ rocketmq_broker_slave_2 }}"

- name: Wait for slave 2 broker to start
  wait_for:
    host: "{{ item }}"
    port: "{{ rocketmq_broker_port_main }}"
    delay: 10
    timeout: 640
    state: started
  with_items:
    - "{{ rocketmq_broker_slave_2 }}"
