- name: Ensure fs exists on data device (if provided)
  filesystem:
    fstype: "{{ storage_fs_type }}"
    dev: "{{ storage_device }}"

- name: Ensure mount point exists
  file:
    state: directory
    path: "{{ storage_path }}"

- name: Ensure data direcory is mounted
  mount:
    path: "{{ storage_path }}"
    src: "{{ storage_device }}"
    fstype: "{{ storage_fs_type }}"
    state: mounted

- name: Ensure data directory has correct owner
  file:
    state: directory
    path: "{{ storage_path }}"
    owner: '65534'
