---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, ec2_name: eventstore_cluster, aws_ami_id: ami-6d48500b, count: 3, ec2_groups: ['ssh_access', 'default', 'eventstore_access'], aws_instance_type: t2.small, ec2_tag_group: Eventstore}
  
- hosts: eventstore
  become: true
  roles:
  - role: eventstore
