---
- hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_REGION: "{{ aws_region }}"

  tasks:
    - name: Gather EC2 instances facts
      ec2_instance_info:
        filters:
          "tag:kind": mqperf-instance
      register: ec2_facts

    - name: Terminate mqperf instances
      ec2:
        instance_ids: "{{ ec2_facts.instances|map(attribute='instance_id')|list }}"
        state: absent
        wait: true
      when: ec2_facts.instances|length > 0

